### ISSUE TITLE
Filenames not compatible with Windows

### ISSUE THREAD

**Issue by ybressler** [ybressler/Broadway-Open-Data#2]
The following characters are not allowed for file names in windows:
```
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)
```
Change code in the function `get_usable_name()` located in `utils/web_scraping.py`

**Code for the function is here:**
```
def get_usable_name(url, ext=".txt"):

    file_name = re.sub("[\/\.:]", "_", url) + ext
    return file_name
```

**Comment by ybressler** [comment]
This is not letting users on windows computers to access our content.

**Comment by ybressler** [comment]
Fixed the code in the new branch `fix-filename-compatibility-yb`. Next, need to rename all files (and directories) so that all files will be renamed – instead of redownloaded...

**Comment by ybressler** [comment]
Should be fixed. Verify if your git synchs up correctly @effieklestz  –– note, you'll need to switch to the master branch before testing...

**Comment by effieklestz** [comment]
Bug fixed! Git synchs up correctly on Windows
